title: "Ross Elder"
#logo: /images/Untitled design (48).png
description: "Statistics/Mathematics Educator with +17 years of experience - Looking for a career in Data Analytics / Data Science"
#show_downloads: true
#google_analytics:
link: "https://www.linkedin.com/in/ross-elder/"
location: "Plano, TX"
social-network-links:
  email: "ross13elder@gmail.com"
  github: ross13elder.github.io
  linkedin: https://www.linkedin.com/in/ross-elder/
share-links-active:
  linkedin: true




theme: "jekyll-theme-minimal"
