title: "Ross Elder"
#logo: /images/Untitled design (48)png
description: "Statistics/Mathematics Educator with +17 years of experience - Looking for a career in Data Analytics / Data Science"
#show_downloads: true
#google_analytics:
link: "https://www.linkedin.com/in/ross-elder/"
location: "Plano, TX"
theme: "jekyll-theme-minimal"
